spring:
  application:
    name: user
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://14.103.203.44/communicationOfStudy?useSSL=false&serverTimezone=UTC
    username: root
    password: wd199604070010!
  redis:
    host: 14.103.203.44
    port: 6379
    password: wd199604070010!
  rabbitmq:
    host: 14.103.203.44
    port: 5672
    username: dev
    password: wd199604070010!
    virtual-host: VirtualHost
server:
  port: 8081


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 日志实现类
    map-underscore-to-camel-case: true  # 开启驼峰命名转换
    cache-enabled: true  # 开启二级缓存
  mapper-locations: classpath*:mapper/*.xml  # Mapper XML 文件路径
  type-aliases-package: com.example.user.entity  # 实体类包路径

api:
  key:
    971b8ff2-02d7-4ed5-9d39-67c0955e55c4