spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://14.103.203.44/flower?useSSL=false&serverTimezone=UTC
    username: root
    password: wd199604070010!

  redis:
    host: 14.103.203.44
    port: 6379
    password: wd199604070010!
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: 100
  rabbitmq:
    host: 14.103.203.44
    port: 5672
    username: dev
    password: wd199604070010!
    virtual-host: VirtualHost
server:
  port: 8080

mybatis:
  configuration:
    #日志等级
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #驼峰命名与下划线自动匹配
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mappers/*xml
  type-aliases-package: com.example.order.model