spring:
  application:
    name: excel
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.120.67.119/flower?useSSL=false&serverTimezone=UTC
    username: root
    password: wd199604070010!
  data:
    redis:
      host: 47.120.67.119
      port: 6379
      password: wd199604070010!
  rabbitmq:
    host: 47.120.67.119
    port: 5672
    username: admin
    password: admin
    virtual-host: my_vhost
    listener:
      simple:
        prefetch: 1
server:
  port: 8083

mybatis:
  configuration:
    #日志等级
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #驼峰命名与下划线自动匹配
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mappers/*xml
  type-aliases-package: com.example.order.model